### ISSUE TITLE
error loading mods

### ISSUE THREAD

**Issue by scooper1** [SnickCH/InsurgencySandstormDedicatedServer#5] opened 2022-03-24 02:00 UTC
**Describe the bug**
log errors on loading mods except vampirism 

`[2022.03.24-01.43.09:613][  0]LogGameMode: Display: Attempting to initialize mutators from list: Medic, ImprovedAI, ScaleSurvival, Vampirism, sBomber, PrintCount, JoinLeaveMessage, MoreAmmo
[2022.03.24-01.43.09:613][  0]LogGameMode: Warning: Mutator path 'Medic' is invalid ().
[2022.03.24-01.43.09:613][  0]LogGameMode: Warning: Mutator path 'ImprovedAI' is invalid ().
[2022.03.24-01.43.09:613][  0]LogGameMode: Warning: Mutator path 'ScaleSurvival' is invalid ().
[2022.03.24-01.43.09:613][  0]LogGameMode: Warning: Mutator path 'sBomber' is invalid ().
[2022.03.24-01.43.09:613][  0]LogGameMode: Warning: Mutator path 'PrintCount' is invalid ().
[2022.03.24-01.43.09:613][  0]LogGameMode: Warning: Mutator path 'JoinLeaveMessage' is invalid ().
[2022.03.24-01.43.09:613][  0]LogGameMode: Warning: Mutator path 'MoreAmmo' is invalid ().
[2022.03.24-01.43.09:628][  0]LogSession: ----- Register Server (SteamNWI) ----- 
[2022.03.24-01.43.09:628][  0]LogSession: ----- Register Server (EOS) ----- 
[2022.03.24-01.43.09:629][  0]LogOnlineSession: OSS: EOS_SessionModification_SetHostAddress(172.17.0.4:7777) returned (EOS_Success)`

**To Reproduce**
start server

**Expected behavior**
full set of mods shown on client connect  

**Screenshots**

**Logfiles / error messages**
If you have logfiles or outputs from the container with the error, please add it.

**System running the container (please complete the following information):**
 - OS: [e.g. Debian Buster x.x.x]
 - Container platform: [e.g. docker version x.x.x]
 - Plase add your docker run command or docker-compose.yml
 - Mainpath with config files: [e.g. /debian/insurgency/]
 - Path for mods (volume): [e.g. /debian/insurgency/Mods/]
 - Container image date: [e.g. 26.11.2021]
 - Did this hapen after a new image or is this the first time you (try) to run the container on this server?:  [eg. first time / since update to the image]

`#Set the container Name, every Container need an unique name (not the GameServer Name)
CNAME=afterdark3

#Optional: if a container with the name sandstorm exist, it will be stopped and deleted
echo docker container will be stopped
docker stop $CNAME
echo docker container will be removed
docker rm $CNAME

#Path to folder where the configs are stored
CONFDIR=/home/steam/insurgency/survival

#Path to folder where the mods should be stored
MODS=/home/steam/insurgency/Mods

#The image that should be used. Don't change it ;)
IMAGE=snickch/insurgencysandstormdedicatedserver:latest

#Set your tokens you get from the next two Pages
#https://gamestats.sandstorm.game/
#https://steamcommunity.com/dev/managegameservers
GSLTTOKEN="F9849FEA31F3347EDE437C2D2A******"
GAMESTATSTOKEN="50816131894D4B7A90C827D328B******"

#Set your mutators for the server you will get it from https://mod.io
#You need an API-Key from https://mod.io/apikey/ which goes to the Engine.ini 
MUTATORS="Medic,ImprovedAI,ScaleSurvival,Vampirism,sBomber,PrintCount,JoinLeaveMessage,MoreAmmo"

#Set the map which should be used on start (ModDownloadTravelTo makes sure your mods are started with the first map and the MaxPlayer you want)
MODTRAVEL="Gap?Scenario=Scenario_Gap_Survival?lighting=day?Password=PASSWORD

#RCON Config
RCONPORT=27015

#Here you can adjust the game ports (Multiple Server need own distinct Ports)
GAMEPORT=7777
QUERRYPORT=27131

#Here starts the script, you shouldn't change anything here, you can all do with the variables above
echo start docker container
docker run -d --restart=always --name $CNAME -p $GAMEPORT:$GAMEPORT/tcp -p $GAMEPORT:$GAMEPORT/udp -p $QUERRYPORT:$QUERRYPORT/tcp -p $QUERRYPORT:$QUERRYPORT/udp -p $RCONPORT:$RCONPORT -p $RCONPORT:$RCONPORT/udp \
--volume $CONFDIR/Game.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Game.ini:ro \
--volume $CONFDIR/Engine.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Engine.ini:ro \
--volume $CONFDIR/Admins.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Admins.txt:ro \
--volume $CONFDIR/Mods.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Mods.txt:ro \
--volume $CONFDIR/MapCycle.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/MapCycle.txt:ro \
--volume $MODS/:/home/steam/steamcmd/sandstorm/Insurgency/Mods \
$IMAGE ./InsurgencyServer-Linux-Shipping -Port=$GAMEPORT -QueryPort=$QUERRYPORT \
-Mods \
-Rcon \
-Mutators=$MUTATORS \
-ModDownloadTravelTo=$MODTRAVEL \
-GSLTToken=$GSLTTOKEN  -GameStatsToken=$GAMESTATSTOKEN`

**Additional context**

**Comment by SnickCH** [comment] 2022-03-24 18:21
Thank you very much for the details. I anser to your first and to this issue.

The "write problem" is unfortunately not reproducable at the moment. I can start the container perfectly without any changes (but there are no mods used). I will try to investigate it a bit more. Could you please give me the details about your system:
- OS  (Ubuntu x.x / Debian x.x. etc.?)
- Plattform (Docker?)

> in the end, i created a steam user and moved the files to that user and changed the owner to root:root
Here I need some more details to check this
- you created a user: "create user steam" ->ok (logic for me)
- "moved the files to that user": What did you do exactly do inside the container? Did you manually just put in "chown steam:steam"?

"Warning: Mutator path 'Medic' is invalid (). " ->The game doesn't find the information about the mods. This is reproducable

Just to be sure: Did you use this config on a VM / paid hoster or is it the first time you are setting up the server? Did you copy the example files 1:1? I guess they are outdated because NWI changed something on the .ini file names.

That the mods did not load: here I found out, that NWI changed the Game.ini to something else or moved parts of it away in another file. This is unfortunately not a container but a NWI issue. I will ask in the steam forum what exactly was changed and if anybody knows more. My servers are running at the moment without mods, this is why I didn't have this issue and until now, nobody reported it (thank you for opening the issue). Here I kindly ask you for some patience.

If you are willing to help troubleshoot, I could create a new tag (like "..:support") and there add the changes. 

Thank you very much in advance for the details, so I can investigate the situation.

**Comment by scooper1** [comment] 2022-03-24 19:23
first time setting up using you exsamples 
will give more info later
but got it going by setting a permison via a samba share on mods directory to everyone

**Comment by SnickCH** [comment] 2022-03-25 10:55
Thank you for the reply. No worries. I opened in the steam forum a thread to ask if anybody has more information if something changed on the .ini files. 

"but got it going by setting a permison via a samba share on mods directory to everyone". here I would really need more information about the setup. I guess that this is not a container but more a setup issue (permissions between the system, system user that runs docker and the mountingpoint into the container). Indeed it is a problem if the write permission is recstricted to this folder (unfortunately). We documented it on the mainpage under 4. (https://github.com/SnickCH/InsurgencySandstormDedicatedServer#4-change-permissions), I hope this helps :)

Just to be sure: Does it work now for you with the mods?
 
I will try my best to help you for the setup. Please let me know, how we can support you  on the setup :)

**Comment by scooper1** [comment] 2022-03-25 11:20
Yes its working for mods
Need to read up how docker maps container user id to host system user id

**Comment by SnickCH** [comment] 2022-03-25 16:17
Thank you very much for the feedback. So it does even work with the medic? Then I know that everything is fine with the container and setup and can close the issue :)

This may help you: 

https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf
https://docs.docker.com/engine/security/userns-remap/

**Comment by scooper1** [comment] 2022-03-25 16:52
I that section 4 of the install doc needs to be reviewed   maybe not using chown instead --user docker option to map uid internal to uid external

**Comment by scooper1** [comment] 2022-03-26 00:00
it was all working ok  until I needed to add a new mod and recreated the container 
now I can't get permissions correct again 
The medic was ok most of the time
I am in the cycle the more you know the worst the problem gets

**Comment by SnickCH** [comment] 2022-03-26 16:42
Thank you for your input. I will take a look at it.

This setup worked for nearly 2 years for many admins on different linux systems. Therefore I guess it has something to do with your setup, if you need to remap the UID of the external to the internal user. This is normally not needed for docker (for any image), if the permissions on the folder (or files) you want to map into the container are set correctly for the user that runs docker. You mentioned "samba share". Therefore I expect that you have a special setup or something, that is different to the other setups. Especially if you recreate the container and it doesnt work. I would guess it has something todo with that share and the permissions. 

If you provide me more details, I can try to help you. At the moment I have no details about your setup. I only know you are doing something with a shared folder. How do you "recreate" the container? What is afterwards not working?

How I did the setup
- Linux: Debian Buster with the newest docker version
- I have a dedicated disk (mountpoint /mnt/disk2/) where I have subfolders for the mods. Each server has it's own subfolder
- There is a user (let's call it "user") that has sudo permissions. With this I did the whole setup
- With this user I created all the folders and files needed for my servers (multiple container on the same VM)

**Comment by scooper1** [comment] 2022-03-26 19:56
Thanks for help 
It appears that using your startup sh file it creates a container on my system that uses  steam as a user name with Id of 1000   1000 on my ubento system is my user scooper1

The server I am using has 27  other docker Containers running   home assistant and frigate wiping is not a option.   I am really mostly doing it to learn how to throw up a container with a game server on it for my friends to play on 

I am trying to understand my lack of knowledge on permission mapping.   The option to change directory owner by samba share was a  bodge on my part and when I recreated container it fell apart 

So will give you more information about my setup. I was really only looking to see if it a normal problem I was having or something I was doing wrong.   When I get a chance I will try get a understanding of how to fix and I will post what I find 

Thanks

**Comment by scooper1** [comment] 2022-03-26 21:23
checking all my working containers on my system 
ever one of them uses an internal id of 0  same for gid 0
for some reason your container is created with id of 1000 and gid 1000   
do not know if i am doing it wrong somehow

Operating System
Ubuntu 20.04.4 LTS
Docker version
19.03.3

i create container using the following commands

`#Set the container Name, every Container need an unique name (not the GameServer Name)
CNAME=afterdark3

#Optional: if a container with the name sandstorm exist, it will be stopped and deleted
echo docker container will be stopped
docker stop $CNAME
echo docker container will be removed
docker rm $CNAME

#Path to folder where the configs are stored
CONFDIR=/home/steam/insurgency/survival

#Path to folder where the mods should be stored
MODS=/home/steam/insurgency/Mods

#The image that should be used. Don't change it ;)
IMAGE=snickch/insurgencysandstormdedicatedserver:latest

#Set your tokens you get from the next two Pages
#https://gamestats.sandstorm.game/
#https://steamcommunity.com/dev/managegameservers
GSLTTOKEN="******"
GAMESTATSTOKEN="******"

#Set your mutators for the server you will get it from https://mod.io
#You need an API-Key from https://mod.io/apikey/ which goes to the Engine.ini 
MUTATORS="Medic,ImprovedAI,ScaleSurvival,Vampirism,sBomber,PrintCount,JoinLeaveMessage,MoreAmmo,RedwoodReborn"

#Set the map which should be used on start (ModDownloadTravelTo makes sure your mods are started with the first map and the MaxPlayer you want)
MODTRAVEL="Gap?Scenario=Scenario_Gap_Survival?lighting=day?Password=afterdark123"
#MODTRAVEL="RedwoodReborn?Scenario=Scenario_RedwoodReborn_Checkpoint?lighting=Day?Password=afterdark123"
#Scenario_RedwoodReborn_Checkpoint

#RCON Config
RCONPORT=27015

#Here you can adjust the game ports (Multiple Server need own distinct Ports)
GAMEPORT=7777
QUERRYPORT=27131

#Here starts the script, you shouldn't change anything here, you can all do with the variables above
echo start docker container
docker run -d --restart=always --name $CNAME -p $GAMEPORT:$GAMEPORT/tcp -p $GAMEPORT:$GAMEPORT/udp -p $QUERRYPORT:$QUERRYPORT/tcp -p $QUERRYPORT:$QUERRYPORT/udp -p $RCONPORT:$RCONPORT -p $RCONPORT:$RCONPORT/udp \
--volume $CONFDIR/Game.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Game.ini:ro \
--volume $CONFDIR/Engine.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Engine.ini:ro \
--volume $CONFDIR/Admins.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Admins.txt:ro \
--volume $CONFDIR/Mods.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Mods.txt:ro \
--volume $CONFDIR/MapCycle.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/MapCycle.txt:ro \
--volume $MODS/:/home/steam/steamcmd/sandstorm/Insurgency/Mods \
$IMAGE ./InsurgencyServer-Linux-Shipping -Port=$GAMEPORT -QueryPort=$QUERRYPORT \
-Mods \
-Rcon \
-Mutators=$MUTATORS \
-ModDownloadTravelTo=$MODTRAVEL \
-GSLTToken=$GSLTTOKEN  -GameStatsToken=$GAMESTATSTOKEN
`

**Comment by SnickCH** [comment] 2022-03-27 08:41
I replaced ther est of the token with *****

Thank you for the input with the PID/GID. I'll check this today on a new tag (...:testingPID or something). Here I have to be carefull with the tags, that I don't change anything on the stable one, because it works at the moment for other people (and I don't want to break it). 


At the moment I have the challenge that it works for me and my friends - I'm not able to recreate the issue. Therefore it is really hard for me to troubleshoot. And I still can't really retrace the whole problem, config and commands you are using. Example: You said you have "problems" when you then recreate the container. What is not working? What kind of errors do you have? We have now the starting script (it looks 1:1 from our examples, looks good for me). What else are you doing with the remaping of the PID? Could you please be so specific as possible, the best would be to even post the command and the error. 

I guess  it is a config challenge, maybe with the samba share or the user for docker / you are working with. Otherwise it wouldn't work for so many admins that use it 1:1 with a standard setup. I will write back as soon as I can test something with the PID/GID.

If you like you can join the discord server and PM me directly. It makes it easier for troubleshooting: https://discord.gg/hRJ4P4JP

**Comment by scooper1** [comment] 2022-03-27 09:20
If I override the I'd with --user root   it crashed after s few seconds 
Non of the other docker scripts I seen change the user or the id    there must be reason why you put those in.   
I will try your mods when available
I was going to clone and try removing the id and user change 
I suspect the problem happens because my user id 1000 does not match the internal one.  I did yet try running it in user id 1000 home directory 
It could also be a ubento to debein difference

**Comment by SnickCH** [comment] 2022-03-27 14:23
I just created a new branch "idtesting" in my CI/CD pipeline that should create a :idtesting tag. You could test this, there I removed the ID 1000

I don't know if this is a debian/ubuntu issue. In general docker runs everything with root. You can map it to PUID 1000. I used a steamcmd image (that was used for CSGO) as a template. There it was set to the PUID 1000 (I think for security reasons) - but freankly, it is to long ago and I didn't document it (my bad)
https://docs.linuxserver.io/general/understanding-puid-and-pgid

In 1-2hours you should be able to use the new image. If you could give me some feedback how it went, that would be great :)

**Comment by SnickCH** [comment] 2022-03-27 18:53
The new image for testing is online: 
snickch/insurgencysandstormdedicatedserver:idtesting

Could you be so kind and give me feedback if this worked for you? If yes, I will move it to a more convinient tag and schedule a daily creation like the "latest" tag

**Comment by scooper1** [comment] 2022-03-27 20:26
I will do.  It maybe tomorrow night 
Thanks

**Comment by scooper1** [comment] 2022-03-27 23:08
idtesting version  did not help with file permissions  still getting the same errors
tried under home directory  with scooper1 user which has id of 1000 - still unable to write files

reloaded lastest version  under scooper1 directory  still the write errors in the logs

run up a console and did a ls -l to list directory owner of the highest level of the directory were permissions errors occur and found out that the Config and Saved directories were owned by root and no write permisions for the steam users  - i would have expected this to owned by the steam user ?

`steam@6d36a9508903:~/steamcmd/sandstorm/Insurgency$ ls -l

total 24
drwxr-xr-x 3 steam steam 4096 Mar 27 17:57 Binaries
drwxr-xr-x 3 root  root  4096 Mar 27 22:49 Config
drwxr-xr-x 5 steam steam 4096 Mar 27 17:57 Content
drwxrwxrwx 3 steam steam 4096 Mar 27 22:27 Mods
drwxr-xr-x 4 steam steam 4096 Mar 27 17:57 Plugins
drwxr-xr-x 3 root  root  4096 Mar 27 22:49 Saved
steam@6d36a9508903:~/steamcmd/sandstorm/Insurgency$
`

**Comment by scooper1** [comment] 2022-03-29 00:33
you need to add a volume map for  GameUserSettings.ini 
that is where the mod.io token has to be and i believe it should be removed from engine.ini

**Comment by SnickCH** [comment] 2022-03-29 10:03
> you need to add a volume map for GameUserSettings.ini that is where the mod.io token has to be and i believe it should be removed from engine.ini

Thank you for the input, you are right. I will add this shortly.
Did this solve your problem?

**Comment by SnickCH** [comment] 2022-03-29 10:05
> idtesting version did not help with file permissions still getting the same errors tried under home directory with scooper1 user which has id of 1000 - still unable to write files
> 
> reloaded lastest version under scooper1 directory still the write errors in the logs
> 
> run up a console and did a ls -l to list directory owner of the highest level of the directory were permissions errors occur and found out that the Config and Saved directories were owned by root and no write permisions for the steam users - i would have expected this to owned by the steam user ?
> 
> `steam@6d36a9508903:~/steamcmd/sandstorm/Insurgency$ ls -l
> 
> total 24 drwxr-xr-x 3 steam steam 4096 Mar 27 17:57 Binaries drwxr-xr-x 3 root root 4096 Mar 27 22:49 Config drwxr-xr-x 5 steam steam 4096 Mar 27 17:57 Content drwxrwxrwx 3 steam steam 4096 Mar 27 22:27 Mods drwxr-xr-x 4 steam steam 4096 Mar 27 17:57 Plugins drwxr-xr-x 3 root root 4096 Mar 27 22:49 Saved steam@6d36a9508903:~/steamcmd/sandstorm/Insurgency$ `

I checked this. This is also in the main (latest) container. I don't think that this is the issue - otherwise it wouldn't work for so many admins. 

At the moment I have some problems too with the mods - but based on Mod.Io and the API access. This is new, since Mod.IO or NWI changed the Mod.IO-API Key to GameUserSettings.ini 

I'm in contact with other server admins and hope that I get there the missing piece of information to solve the issue.

I'm sorry that we don't have more information at the moment

**Comment by scooper1** [comment] 2022-03-29 10:07
Yes its a lot better now 
It took ages to find because I accepted that original code was working ok  when it was not due to a change outside of your control

**Comment by scooper1** [comment] 2022-03-29 10:11
Plus there maybe still the directory root issue with mods directory
May I make a suggestion 
Map whole directories not the individual files  as this will protect you against more new files in use

**Comment by SnickCH** [comment] 2022-03-29 10:33
> Yes its a lot better now It took ages to find because I accepted that original code was working ok when it was not due to a change outside of your control

Thank you for the feedback. What do you mean with better? Is there still something that doesnt work? 

I'm sorry that we missed this change from NWI. NWI does not inform it's community, a lot of update did in the paths break the servers/game. I try to get in touch with NWi since over 1.5 years, but they are just not intersted in working with the community together. This makes the work for this project where difficult. 
The project (if this is the "original code " you are refering) worked perfectly until NWI changed this file. it also works perfectly, just without mods. Unfortunately you are the first that reports this issue (thank you for that). I can only guess, that the other admins did just change it in their startup script but didn't report it here. From the downloads / week I see much more then from one year before. 

I hope that you will now profit from the project with much less daily admin work for your server(s) :)

**Comment by SnickCH** [comment] 2022-03-29 10:45
> Plus there maybe still the directory root issue with mods directory May I make a suggestion Map whole directories not the individual files as this will protect you against more new files in use

Thank you for the input - inputs are allways welcome 👍 
 It would be easier if this are the only files inside this folders. And here it starts: if you have other files that come with the container, you don't want to map the whole folder. We don't update anything inside the container that is running, we provide a full container with all updated files that are needed. At the moment it would work, because only the config files are there (as far as I see it) - until NWI changes again things at it's structure. NWI broke a lot of things in the past....

Here we have to make a decision

- Do we want to have the script shorter (mount folders) 
- or do we want to make sure, if something changes inside, it keeps working
- We do this in our spare time, so we did make sure, that we keep the troubleshooting and issue footprint as small as possible. Now it probably bakefired because it didn't change inside the container - it was a new file that comes from "outside".
- 
I hope you now better understand why we made this decision. It is always a pro/contra - at the moment I don't see the perfect solution.

I will discuss with N0ri if we will provide another script where we mount the whole folder and tag this script under "beta" - people can use it at their own risk. 


"Plus there maybe still the directory root issue with mods directory"
I checked it inside a new container: The owner of the mod folder is the user steam:
drwxr-xr-x 3 steam steam 4.0K Dec 27 15:38 Mods

**Comment by SnickCH** [comment] 2022-04-04 08:15
@scooper1 N0ri updated the examples with the GameUserSettings.ini They are tested and worke on his environment. 

Can you please confirm that the problem is solved or provide us more information? Thank you very much

**Comment by SnickCH** [comment] 2022-04-08 12:43
@scooper1 We didn't hear from you for nearly 10 days - therefore I close this issue. 
The new example with the correct GameUserSettings.ini is online and working.

**Closed as completed by SnickCH** 2022-04-08 12:43 UTC

**Comment by scooper1** [comment] 2022-04-08 13:25
sorry not had time to test

**Comment by SnickCH** [comment] 2022-04-08 13:49
@scooper1 no worries. 
We have tested the new setup on more then 2 servers and it fully works. So I guess it will work on your system to (Debian or Ubuntu). If you experience any other issues or have questions, just feel free to open a new issue
