### ISSUE TITLE
[BUG] `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by darkymtp** [SnickCH/InsurgencySandstormDedicatedServer#8] opened 2023-11-04 14:27 UTC
Hello.

The image doesn't start anymore.

Docker logs shows : 

```./InsurgencyServer-Linux-Shipping: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.26' not found (required by /home/steam/steamcmd/sandstorm/Insurgency/Binaries/Linux/../../Plugins/HydraInterface/HydraSDK/lib/Linux/libpros.sdk.linux.x64.so)```

Latest image
Docker version 24.0.7, build afdd53b
Debian 11.8 up to date
Kernel : Linux debian 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux

Thanks !

**Comment by SnickCH** [comment] 2023-11-05 13:02
@darkymtp Thank you very much for providing all the information in the issue - appreciated. 

"The image doesn't start anymore." ->Therefore I assume you used the same image (older build) with the exact same settings 1:1, the only thing that changed was the image. 

I will check today if I can reproduce it in my test environment (and then fix it). I don't have any productive sandstorm server anymore (I still keep the project up & running for the ones using it).

**Comment by SnickCH** [comment] 2023-11-05 13:05
@darkymtp  Did you also test latest image (12 hours ago)? Thank you in advance for the short feedback

**Comment by SnickCH** [comment] 2023-11-05 13:30
@darkymtp  I just saw from two other repos (not mine) that they have the same issue with the steam CMD client since September / October.

It could be aproblem with the lib32gcc package and/or symlinks we are using (at least this is what I see from the other repos). I replaced it with a never version and started a new tag for testing ("testing"). This new image with the specific testing tag will be ready in 1-2 hours (it needs time to build). Could you be so kind and test the "testing" tag for me ( as soon as the image is build)? 

I want first to try it in testing before pushing it to latest. Thank you in advance for your help with testing

**Comment by darkymtp** [comment] 2023-11-06 08:31
Hello.

The testing version seems to work, I can't play right now but the server is up.
Thanks !

**Comment by SnickCH** [comment] 2023-11-06 12:54
@darkymtp Thank you for the feedback. I'l wait until you have tested it. If you confirm, that it works (played), I'll push it to latest

**Comment by darkymtp** [comment] 2023-11-06 17:03
It works.

**Comment by SnickCH** [comment] 2023-11-06 17:45
@darkymtp Thank you very much for testing it. I will push the change to production (latest) and close the issue.

**Closed as completed by SnickCH** 2023-11-06 17:45 UTC
Labels: bug
